### ISSUE TITLE
Cookie manager

### ISSUE THREAD

**Issue by slavastartsev** [bob-collective/ui#300]
Integrate `Cookieyes` service into
- evm
- bob-pay

*_Detailed cookie banner customisation will be enabled once trial period ends_

**Comment by slavastartsev** [comment]
Css customisation is only available for gobob.xyz (not preview). 
To check production results go to https://app.cookieyes.com/customize -> credentials in 1Password

custom css to override defaults
```css
/* use !important instead of increasing selector specificity e.g. 2x class selector */
/* button */
.cky-btn {
  border-radius: 8px !important;

  transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform !important;
  transition-duration: 200ms !important;
  outline: none !important;
}
.cky-btn-reject:hover,
.cky-btn-customize:hover,
.cky-btn-preferences:hover {
  /* override inline styles */
  background-color: rgb(49, 56, 70) !important;
}
/* link */
.cky-show-desc-btn {
  color: rgb(255, 255, 255) !important;
  text-decoration: underline !important;
}
.cky-show-desc-btn:hover {
  opacity: 0.75 !important;
  text-decoration: underline !important;
}
/* Always active label */
.cky-always-active {
  color: rgb(243, 93, 0) !important;
}
/* Sidebar */
.cky-modal.cky-sidebar-left.cky-modal-open {
  border-right: 1px solid rgb(49, 56, 70) !important;
}
/* Modal */
.cky-consent-container .cky-consent-bar {
  box-shadow: none !important;
}
```

Production examples
| Modal | Preference Sidebar | Preference Modal | Preference Push down | Banner |
|--------|--------|--------|--------|--------|
| <img width="487" alt="image" src="https://github.com/user-attachments/assets/d58acf14-4b58-495d-aa12-d74f109b7181"> | <img width="499" alt="image" src="https://github.com/user-attachments/assets/bab36aaa-994a-4a6c-bd0c-6811e4b30672"> | <img width="873" alt="image" src="https://github.com/user-attachments/assets/54a74932-514c-4234-89ac-4c352c146b55"> | <img width="960" alt="image" src="https://github.com/user-attachments/assets/e7db805f-ea4a-42d8-b467-f938939a6709"> | <img width="965" alt="image" src="https://github.com/user-attachments/assets/f7af054d-ce14-43b2-912b-516221ec83ca"> |

Texts are subject to change through admin panel
